// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOwuCKo4qiyueuv2lfR2G2wpQIdnfT11Y',
    appId: '1:551608628054:web:470d36331c85311c505cf7',
    messagingSenderId: '551608628054',
    projectId: 'tasks-compelecated',
    authDomain: 'tasks-compelecated.firebaseapp.com',
    storageBucket: 'tasks-compelecated.firebasestorage.app',
    measurementId: 'G-2VDRW8PWHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8LV7qN5R89WocHMHBKZJqgijaNIzkijg',
    appId: '1:551608628054:android:5a45126ccef1222f505cf7',
    messagingSenderId: '551608628054',
    projectId: 'tasks-compelecated',
    storageBucket: 'tasks-compelecated.firebasestorage.app',
    androidClientId: 'YOUR_WEB_CLIENT_ID.apps.googleusercontent.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qj3w7yxeZpnpc_Nn_cDc-O1-xgnRpVU',
    appId: '1:551608628054:ios:ad783dd12aa1ea91505cf7',
    messagingSenderId: '551608628054',
    projectId: 'tasks-compelecated',
    storageBucket: 'tasks-compelecated.firebasestorage.app',
    iosBundleId: 'com.example.tasksCompeleted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qj3w7yxeZpnpc_Nn_cDc-O1-xgnRpVU',
    appId: '1:551608628054:ios:ad783dd12aa1ea91505cf7',
    messagingSenderId: '551608628054',
    projectId: 'tasks-compelecated',
    storageBucket: 'tasks-compelecated.firebasestorage.app',
    iosBundleId: 'com.example.tasksCompeleted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOwuCKo4qiyueuv2lfR2G2wpQIdnfT11Y',
    appId: '1:551608628054:web:622da243eb8a375b505cf7',
    messagingSenderId: '551608628054',
    projectId: 'tasks-compelecated',
    authDomain: 'tasks-compelecated.firebaseapp.com',
    storageBucket: 'tasks-compelecated.firebasestorage.app',
    measurementId: 'G-PBZ2LN861V',
  );
}
